### ISSUE TITLE
HTML and e-mail contents issue

### ISSUE THREAD

**Issue by surferjoeit** [itprojects/InboxPager#36] opened 2020-04-22 11:57 UTC
Hello,
first of all many thanks for the app!
Unfortunately i encountered a couple of issues:
with smtp: smtp.tiscali.it i can't send emails, the following error dialogue appears: EHLO requires valid address
with smtp: mail.keytech.it i can send e-mails but no email is saved in sent folder on imap server.
Many thanks
Francesco

**Comment by itprojects** [comment] 2020-04-22 19:24
For: mail.keytech.it

Different servers will have different server policies. By design, this is not part of Inbox Pager. For example gmail automatically saves a copy, unless setup otherwise.

For: smtp.tiscali.it

The error suggests an invalid address.

@surferjoeit  Which Inbox Pager version are you using?

Have you enabled SSL/TLS access for that server?

Are you sure `smtp.tiscali.it` is the correct outgoing server?

What port are you using?

Did you test with "Try Outgoing" in account settings for that mailbox?

Can you receive incoming (IMAP) messages?

**Comment by surferjoeit** [comment] 2020-04-23 07:12
Thanks for your feedback, i really like the minimalist approach of the app and would like to use it.

About mails not saved in sent folder: i understand, but with other clients i do not have such kind of issue.
About smtp.tiscali.it:
I'm using latest release, downloaded with f-droid.
I confirm SSL/TLS access for that server. It's not possible to access in any other way.
I'm sure smtp is properly configured on 465 port
If i test with "Try Outgoing" i get the following error:
Problem 
Attempt to write to field 'boolean net.inbox.dialogs.SpinningStat us.unb|ock' on a null object reference 

net.inbox.server.Handler:289
net.inbox.server.SMTP2770
net.inbox.server.SMTP:299
net.inbox.server.SMTP281
net.inbox.server.Socketh:93
java.lang.Thread:761 

Incoming mails are properly received, even if HTML is not properly rendered. Most of the messages are shown in plain text with all tags so they're not readable. If i try to change to html view a "NO Text" is shown.

Many thanks

**Comment by itprojects** [comment] 2020-04-23 14:28
> About mails not saved in sent folder: i understand, but with other clients i do not have such kind of issue.

By design, Inbox Pager is not a replacement for traditional e-mail clients. If you want copies of sent emails, you need to use see if your server has this automatic function, and switch it on from the server's website.

> Incoming mails are properly received, even if HTML is not properly rendered.

This is because the element used to display the HTML message is sandbox-ed form the internet. This way malicious code cannot execute, but you do get to see the text of the message. There will also be less advertising.

> If i try to change to html view a "NO Text" is shown.

That could be a broken message. If something went wrong in either downloading the message, or, the original message was badly formatted.

Does this happen to all of your messages, that have HTML? On both accounts?

>  If i test with "Try Outgoing" i get the following error:

The error is interesting, but probably not the one we're looking for.

Try Auto Test, and Try Incoming.

**Comment by surferjoeit** [comment] 2020-04-23 14:58
> > If i try to change to html view a "NO Text" is shown.
> 
> That could be a broken message. If something went wrong in either downloading the message, or, the original message was badly formatted.
> 
> Does this happen to all of your messages, that have HTML? On both accounts?
> 
It happens on most of them. Only messages that are html only are (almost) properly formatted. Messages which come with both (plain/html) formats have the "NO TEXT" issue.

> Try Auto Test, and Try Incoming.
Try incoming is ok.
Auto test generates the following error:
![Screenshot_2020-04-23_16-49-51](https://user-images.githubusercontent.com/26968284/80114227-9c6fbd00-8583-11ea-9a00-42556408485a.jpg)

**Comment by itprojects** [comment] 2020-04-23 16:34
@surferjoeit  Thank you for the screenshot.

It appears the server doesn't like sending on the typical ports. Maybe they've changed them; or that feature costs money/premium subscription; email tech support for that server and ask them why that is. It may or may not be the case that the server's SMTP support has to be enabled from their website. Alternatively, if you have a firewall, it can be blocking those ports. Hopefully, the server does not require STARTTLS, which is not supported in Inbox Pager.

> It happens on most of them. Only messages that are html only are (almost) properly formatted. Messages which come with both (plain/html) formats have the "NO TEXT" issue.

Unable to replicate. What version is your Android?

**Comment by surferjoeit** [comment] 2020-04-23 18:33
If you check vere:
https://assistenza.tiscali.it/servizi/guida/posta-android/
Server and porta should be ok.. And i set those parameters a lot of time with no issue.
Regarding HTML rendering, i have android 7.1.2.
Thanks a lot

**Comment by itprojects** [comment] 2020-04-23 18:56
SMTP:

Can you try sending from another network, i.e. a wi-fi. Just to see if the SMTP is not a firewall problem.

HTML:

Can you offer a censored screenshot with the words or images blurred?

**Comment by surferjoeit** [comment] 2020-04-24 06:52
I tried sending both from 4G and wifi, same issue.
Here are two screenshots of the same message, plain and HTML:
![plain](https://user-images.githubusercontent.com/26968284/80183322-ea7ad400-8608-11ea-82b5-0fd407b69e16.jpg)
![html](https://user-images.githubusercontent.com/26968284/80183337-eea6f180-8608-11ea-90b0-4ce4bf9c767f.jpg)

**Comment by itprojects** [comment] 2020-04-24 15:05
For the SMTP: Do you have a second Android device, for testing?

For the HTML:

E-mail messages are not like other messages. The same E-mail message can have a plain text message, a html message, and other formats, too. This sub-type of message is called a MIME message.

It's not that HTML doesn't work, it's that it's in the wrong place. For some unknown reason the HTML formatted parts of your message are written to where the plain text should be. This defect could not be reproduced, so it would be useful if you could offer a redacted message's text.

1. Login through a browser into your account.
2. Send yourself a simple message. "Salve, mundo!"
3. Refresh the page to see your new message.
4. Download the `.eml` e-mail message file.
5. Open the `.eml file` it looks something like this:

`MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="----=_NextPart_DC7E1BB5_1105_4DB3_BAE3_2A6208EB099D"

------=_NextPart_DC7E1BB5_1105_4DB3_BAE3_2A6208EB099D
Content-type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

Sample Text Content
------=_NextPart_DC7E1BB5_1105_4DB3_BAE3_2A6208EB099D
Content-type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

<html>
<head>
</head>
<body>
<div style=3D"FONT-SIZE: 10pt; FONT-FAMILY: Arial">Sample HTML =
Content</div>
</body>
</html>

------=_NextPart_DC7E1BB5_1105_4DB3_BAE3_2A6208EB099D--`


6. We only need the block described above, not the email address or headers.

**Comment by surferjoeit** [comment] 2020-04-25 07:00
Hello...
i tried with another device, same issue, no way to send e-mail with smtp.tiscali.it.

HTML: i sent a formatted e-mail from web client. If i open the message with inbox pager i can only see a plain version, no option to switch to HTML.... here is the mime block:

MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_74e1fa18bb696bd7a54d2a18867a9777"


--b1_74e1fa18bb696bd7a54d2a18867a9777
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable


This is a test message.

 - test
 - test



--b1_74e1fa18bb696bd7a54d2a18867a9777
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<head><title></title></head>
<body><div class=3D"iw_mail" dir=3D"ltr">
<p style=3D"margin:0;" dir=3D"ltr"><span style=3D"font-weight: bold;">This<=
/span> is a test message.</p>
<ul>
<li>test</li>
<li>
<span style=3D"text-decoration: underline;">test</span><br>
</li>
</ul>
<div class=3D"signature"></div>
</div></body>

**Comment by itprojects** [comment] 2020-04-25 13:47
In the Mime part of the e-mail is there anything like:

`--b1_74e1fa18bb696bd7a54d2a18867a9777--`

at the end?

**Comment by itprojects** [comment] 2020-04-25 14:54
In SMTP:

No client certificate CA names sent

In IMAP:

No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-384, 384 bits

IMAP works, SMTP does not.

One reason this can be is:

SSL routines:tls_process_ske_dhe:dh key too small

In other words, something is less than perfect with the SSL certificagte in SMTP.

This is not an Inbox Pager bug, whatever the cause.

**Comment by surferjoeit** [comment] 2020-04-26 13:59
> 
> 
> In SMTP:
> 
> No client certificate CA names sent
> 
> In IMAP:
> 
> No client certificate CA names sent
> Peer signing digest: SHA256
> Peer signature type: RSA
> Server Temp Key: ECDH, P-384, 384 bits
> 
> IMAP works, SMTP does not.
> 
> One reason this can be is:
> 
> SSL routines:tls_process_ske_dhe:dh key too small
> 
> In other words, something is less than perfect with the SSL certificagte in SMTP.
> 
> This is not an Inbox Pager bug, whatever the cause.

Ok, thanks. Any chance to overcome this? Other apps are able to send anyway through this smtp.

**Comment by surferjoeit** [comment] 2020-04-26 14:05
> 
> 
> In the Mime part of the e-mail is there anything like:
> 
> `--b1_74e1fa18bb696bd7a54d2a18867a9777--`
> 
> at the end?

Yeah there was... sorry, i forgot to copy it..

**Comment by itprojects** [comment] 2020-04-26 14:48
This could be a server problem. SMTP and IMAP have the same certificate, but a different implementation. If IMAP works, and it does, then the SMTP implementation is a problem.

> Ok, thanks. Any chance to overcome this?

There's a risk of breaking security, to accommodate. Better to use one of the other e-mail clients for this account, for now.

The HTML error, does it happen on `mail.keytech.it` ?

Try the following:

1. Make a new account in Inbox Pager for `mail.keytech.it`
2. Save it.
3. Close the app. Open the app.
4. Go to the new account.
5. Refresh it.
6. Go to menu "Error / Exceptions"

Report here, you can remove private information.

**Comment by surferjoeit** [comment] 2020-04-27 06:29
HTML issue happens on both accounts. I followed your instructions, but no error is reported. I think it's related to messages themselves, or better to mail client used to send messages, rather than the server. Could it be?

**Comment by itprojects** [comment] 2020-04-27 17:55
Quoted-printable is how non-english alphabets are safely transferred between e-mail servers. Some clients use this all the time. Inbox Pager does have some problems with that type of transfer.

The defective message example you gave has:

Content-Transfer-Encoding: quoted-printable`. 

Do the following.

1. Set aside 1 hour, if you can.
2. Record the names of 3 defective HTML e-mails, seen in Inbox Pager.
3. Record the names of 3 acceptable HTML e-mails, seen in Inbox Pager. An HTML e-mail is acceptable even if you don't see all the images, so far as you **don't see** `NO TEXT` and `<html xmlns:...` like in the screenshots.
4. Login via browser.
5. See the full e-mail messages. You may need to download them.
6. Report the statistics:
How many defectives have quoted-printable?
How many acceptables have quoted-printable?

**Comment by surferjoeit** [comment] 2020-04-29 09:37
> 
> 
> Quoted-printable is how non-english alphabets are safely transferred between e-mail servers. Some clients use this all the time. Inbox Pager does have some problems with that type of transfer.
> 
> The defective message example you gave has:
> 
> Content-Transfer-Encoding: quoted-printable`.
> 
> Do the following.
> 
>     1. Set aside 1 hour, if you can.
> 
>     2. Record the names of 3 defective HTML e-mails, seen in Inbox Pager.
> 
>     3. Record the names of 3 acceptable HTML e-mails, seen in Inbox Pager. An HTML e-mail is acceptable even if you don't see all the images, so far as you **don't see** `NO TEXT` and `<html xmlns:...` like in the screenshots.
> 
>     4. Login via browser.
> 
>     5. See the full e-mail messages. You may need to download them.
> 
>     6. Report the statistics:
>        How many defectives have quoted-printable?
>        How many acceptables have quoted-printable?

Here are some stats, sorry for this wait but i've been busy:

Defective: 4 (quoted printable: 3)
Acceptable: 4 (quoted printable: 1)

**Comment by itprojects** [comment] 2020-04-29 13:23
We have found the HTML bug. In failing to process the `quoted-printable` contents, Inbox Pager either handles the error by saying "NO TEXT", although that should have been "ERROR: CONVERTING TEXT".

This bug will be difficult to fix. Some very deep changes will be needed. Maybe a newer minimum version of Android will be required.

This bug will stay open/unfixed for the foreseeable future.

**Comment by surferjoeit** [comment] 2020-04-29 13:41
Ok, thanks.

**Comment by itprojects** [comment] 2020-05-24 13:49
Fix in v5.0.

**Closed by itprojects** 2020-05-24 13:49 UTC
