### ISSUE TITLE
[BUG] Can't sync mails on device

### ISSUE THREAD

**Issue by PercevalSA** [itprojects/InboxPager#29] opened 2019-10-28 21:49 UTC
The application can't sync my gmail account. After adding a Gmail account and press the sync button a pop-up appears with "a0 BAD Too many argument provided [16 alphanumeric string]".

Device : OnePlus One
Android version : LineageOS 16.0 (Android 9)
InboxPager version tested : Latest from F-droid and compiled from sources 

"RUN" tab :

019-10-28 22:25:57.985 3187-3245/system_process I/system_server: Background concurrent copying GC freed 149220(8MB) AllocSpace objects, 354(8MB) LOS objects, 42% free, 15MB/27MB, paused 129us total 207.684ms
2019-10-28 22:26:13.746 19824-19904/net.inbox.pager D/OpenGLRenderer: endAllActiveAnimators on 0x91344100 (RippleDrawable) with handle 0x91c08f90
2019-10-28 22:26:13.933 288-397/? W/SurfaceFlinger: Attempting to set client state on removed layer: net.inbox.pager/net.inbox.InboxPager#1
2019-10-28 22:26:13.933 288-397/? W/SurfaceFlinger: Attempting to destroy on removed layer: net.inbox.pager/net.inbox.InboxPager#1
2019-10-28 22:26:15.432 19824-19904/net.inbox.pager W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2019-10-28 22:26:15.433 19824-19904/net.inbox.pager D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
2019-10-28 22:26:15.635 288-2871/? D/SurfaceFlinger: duplicate layer name: changing net.inbox.pager/net.inbox.InboxPager to net.inbox.pager/net.inbox.InboxPager#1
2019-10-28 22:26:15.650 19824-19904/net.inbox.pager W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2019-10-28 22:26:15.650 19824-19904/net.inbox.pager D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
2019-10-28 22:26:16.115 288-2871/? W/SurfaceFlinger: Attempting to set client state on removed layer: ?#0
2019-10-28 22:26:16.115 288-2871/? W/SurfaceFlinger: Attempting to destroy on removed layer: ?#0

"Logcat" Tab :

2019-10-28 22:46:44.525 3187-3792/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2019-10-28 22:46:44.588 5038-5038/com.android.phone D/ServiceStateProvider: subId=1
2019-10-28 22:46:56.077 2902-2902/? W/wificond: Copy constructor is only used for unit tests
2019-10-28 22:46:56.077 2902-2902/? W/wificond: Failed to get NL80211_ATTR_EXT_FEATURES
2019-10-28 22:46:56.078 2902-2902/? W/wificond: Copy constructor is only used for unit tests
2019-10-28 22:46:56.078 2902-2902/? W/wificond: Failed to get NL80211_ATTR_EXT_FEATURES
2019-10-28 22:46:56.079 2902-2902/? W/wificond: Copy constructor is only used for unit tests
2019-10-28 22:46:56.079 2902-2902/? W/wificond: Failed to get NL80211_ATTR_EXT_FEATURES
2019-10-28 22:46:56.106 5785-12553/com.google.android.gms I/Authzen: [DeviceStateSyncManager] The server is in sync with current state. Nothing to do
2019-10-28 22:46:56.770 19824-19904/net.inbox.pager W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2019-10-28 22:46:56.772 19824-19904/net.inbox.pager D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
2019-10-28 22:46:58.610 3187-28603/system_process D/WificondControl: Scan result ready event
2019-10-28 22:46:58.611 3187-3800/system_process I/EthernetTracker: interfaceLinkStateChanged, iface: wlan0, up: true
2019-10-28 22:46:59.005 19824-19904/net.inbox.pager W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2019-10-28 22:46:59.005 19824-19904/net.inbox.pager D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
2019-10-28 22:46:59.030 288-397/? D/SurfaceFlinger: duplicate layer name: changing Dim Layer for - Task=1056 to Dim Layer for - Task=1056#1
2019-10-28 22:46:59.130 288-1840/? W/SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=1056#0
2019-10-28 22:46:59.130 288-1840/? W/SurfaceFlinger: Attempting to set client state on removed layer: ?#0
2019-10-28 22:46:59.130 288-1840/? W/SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=1056#0
2019-10-28 22:46:59.130 288-1840/? W/SurfaceFlinger: Attempting to destroy on removed layer: ?#0
2019-10-28 22:47:01.213 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@566f877 HexData = [010000000404000012000000514f454d484f4f4b1d04080002000000ffff]
2019-10-28 22:47:01.213 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0
2019-10-28 22:47:01.213 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: Response ID 525341 is not served in this process.
2019-10-28 22:47:01.213 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps
2019-10-28 22:47:01.214 8501-8501/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelIfaceManager: handleMessage what = 0
2019-10-28 22:47:01.218 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@566f877 HexData = [010000000404000016000000514f454d484f4f4bf0030800060000002d312c312c39]
2019-10-28 22:47:01.218 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: Rcvd UNSOL response with 32 bytes data for SUB0
2019-10-28 22:47:01.218 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: WifiSafeChannels [45, 49, 44, 49, 44, 57]
2019-10-28 22:47:01.218 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: Decoded string -1,1,9
2019-10-28 22:47:01.218 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: Parsed channels [-1, 1, 9]
2019-10-28 22:47:01.219 8501-8518/com.qualcomm.qcrilmsgtunnel D/QcrilMsgTunnelSocket: Broadcasting intent ACTION_SAFE_WIFI_CHANNELS_CHANGED 
2019-10-28 22:47:01.220 3187-3291/system_process E/ActivityManager: Sending non-protected broadcast qualcomm.intent.action.SAFE_WIFI_CHANNELS_CHANGED from system uid 1001 pkg null
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21386)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:21986)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22128)
        at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10175)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:167)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3377)
        at android.os.Binder.execTransact(Binder.java:731)
2019-10-28 22:47:01.239 3187-3792/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2019-10-28 22:47:01.239 3187-3792/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2019-10-28 22:47:01.302 5038-5038/com.android.phone D/ServiceStateProvider: subId=1

**Comment by itprojects** [comment] 2019-10-30 12:02
> a0 BAD Too many argument provided [16 alphanumeric string]

Can be due to a bad inbox configuration. Does yours look like this:

Username: user.name@gmail.com
IMAP: 993 imap.gmail.com
SMTP: 465 smtp.gmail.com

Did you try multiple networks? Cellular and wi-fi?

Lineage OS (16) is known to work with Inbox Pager, maybe this is a new Lineage OS bug, can you update your Lineage OS?

The specific Adreno GPU, that you are using, is also known to work with Inbox Pager.

Gmail is known to work without problems, at this time.

**Comment by itprojects** [comment] 2019-10-31 17:45
> a0 BAD Too many argument provided [16 alphanumeric string]

Does Inbox Pager crash after the pop-up? Or does it let you keep using the app??

More logs could be useful, if they are different than the one provided. Please make sure you anonymize all logs - remove user names and passwords.

Can you try POP protocol? (IMAP/POP Switch, but remove port number before saving; you may have to enable POP for gmail from web interface)
Are you sure you have enabled Gmail SSL/TLS access? Google calls it "less secure access".

Can you try another email server? [Must support SSL/TLS]

Have you used different versions of Inbox Pager?

How many emails do you have? Is it hundreds, few thousands, many thousands.

**Comment by itprojects** [comment] 2019-11-08 15:35
@PercevalSA Any comment on the above?

**Comment by itprojects** [comment] 2019-11-26 11:59
Closing this bug due to:

- InboxPager is known to work on this GPU, OS
- Lack of ability to reproduce.

Suggestion for those experiencing this bug - update your OS/rom.

**Closed by itprojects** 2019-11-26 11:59 UTC
