### ISSUE TITLE
Support STARTTLS

### ISSUE THREAD

**Issue by zabbal** [itprojects/InboxPager#8] opened 2016-10-08 22:17 UTC
Some mail servers use STARTTLS command instead of separate TLS port. Would be nice if those are supported as well (both imap and smtp).

**Comment by itprojects** [comment] 2016-10-09 08:12
Have you tested such a server?
Have you tested such a server with InboxPager?
InboxPager comes with test tools, see edit account activity in the app. Have you used them?
Can you give a more detailed outline? You can change the names of the servers & ip's, too.

**Comment by zabbal** [comment] 2016-10-12 20:53
My bad, I've re-tested with TLS server and got the same error as with STARTTLS so it got to be smth else.
When I press "Try incoming" in account settings I got popup "Authentication" with empty string with "Other: -1" right below it.

I'm using v1.0 installed from f-droid. Is there a way to get debug logs or somehow else aid in debugging this?

**Comment by itprojects** [comment] 2016-10-13 17:53
"same error as with STARTTLS"

In which app - InboxPager? or in another app, if other, please specify!

The "-1" error could be a bad configuration for example:

wrong.gmail.com is WRONG
imap.gmail.com should work

If you want to send emails, you need to specify smtp-server, explicitly!
smtp.gmail.com

If that field is empty -> no sending is enabled, by design

Is this server internationally know, or is it a local geographically limited service?

Can you ping the IP of the server, maybe with a concrete IP (i.e. 10.0.0.1, not a real example) the error cold be specifically by-passed?

Can you figure out if this server uses standard certificates, or self-signed certificates?

Also very important:

Which port are you using?(THIS IS VERY IMPORTANT)
Got a NAT, firewall, etc.?

What quick is your network? Speedtest-ed it?

What is the format of your username:

user.name@myserver.com

OR

user.name

Any & every server information would be very useful - pop?imap?smtp?ports?

There is an event log menu button, it may yield some clues.

Debugging should be possible through ADB, with Android Studio installed.

1. Install Android Studio

2. Go to adb tab (lower part of the app)

3. Connect your android via usb

4. Use the app to make the error

5. Error and exceptions should appear in there, if any occur.

LAST RESORT: One option would be to clear the app's private data, reinstall from f-droid. Probably won't help, but if it does, it could be interesting.

**Comment by zabbal** [comment] 2016-11-20 13:21
Would it be possible to add some more elaborate error messages in future versions? Having only "-1 smth is wrong" does not give much options for users willing to help with troubleshooting.

In my particular case:

It works with gmail, fails with alumni.ntnu.no - so it's not connectivity issue. The account data or both is taken from thunderbird where it works fine.

Here is config data:
imap.alumni.ntnu.no:143
smtp.alumni.ntnu.no:587
account: user@alumni.ntnu.no
username: user

Btw, to decrease probability of typos would be nice if fields for imap/smtp would be pre-filled with suggested names like imap.x.com & smtp.x.com once user entered account name user@x.com.

**Comment by itprojects** [comment] 2016-11-24 12:56
The fact that you are getting a "-1", and based on the ports, confirms that STARTTLS (command) is definitely not supported. That was the original expectation.

In order to support STARTTLS and SSL a large and difficult patch may be necessary.

Should the pre-fill be wrong, even one symbol, may, give away username and password.

**Comment by itprojects** [comment] 2016-11-24 15:53
**WARNING**!

It seems that the above mentioned server uses:

ECDHE_RSA_WITH_RC4_128_SHA, RSA_WITH_RC4_128_SHA, _and_ sha1WithRSAEncryption.

May be great for non-essential stuff. May wish to omit everything else...

**Comment by itprojects** [comment] 2018-05-12 14:38
For extra transport security - won't fix

**Closed by itprojects** 2018-05-12 14:38 UTC
Labels: wontfix
